#!/usr/bin/env python
import unittest
from proxyjs.tests import *

javascript.TestExtractor.fixtures = './examples/'

print "\nRunning Javascript Tests:"
suite = unittest.TestLoader().loadTestsFromModule(javascript)
unittest.TextTestRunner(verbosity=2).run(suite)

print "\nRunning Proxy Tests:"
suite = unittest.TestLoader().loadTestsFromModule(proxy)
unittest.TextTestRunner(verbosity=2).run(suite)